name: mustm3
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1
 
environment:
  sdk: '>=3.0.0 <4.0.0'
 
dependencies:
  flutter:

    sdk: flutter
 
  just_audio: ^0.9.40
  just_audio_background: ^0.0.1-beta.11
  audio_session: ^0.1.21
  webview_flutter: ^4.10.0
  youtube_explode_dart: ^2.3.5
  youtube_player_flutter: ^9.1.1
  permission_handler: ^11.3.1
  path_provider: ^2.1.4
  dio: ^5.4.0
  cached_network_image: ^3.3.0
  shared_preferences: ^2.3.3
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.13.1
  flutter_dynamic_icon: ^2.1.0
  video_thumbnail: ^0.5.3
  on_audio_query: ^2.9.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  video_player: ^2.9.2
  file_picker: ^8.1.4
  url_launcher: ^6.3.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/tajawal.ttf 
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon-white.png"